name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - pete1  # Cambia a la rama que uses (main, master, etc.)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usa la versión de Node.js que necesites

      - name: Navigate to /ino directory
        run: cd ino  # Cambia a la carpeta /ino

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ino/dist/<nombre-de-tu-proyecto>  # Ajusta la ruta según la ubicación de la carpeta dist